title: Your awesome title
author:
  name: Daniel Tenreiro

# The `>` after `description:` means to ignore line-breaks until next key.
description: >
  Lorem ipsum.

# Build settings
theme: minima
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
header_pages:
  - about.md

# Minima specific settings, available from Minima 3.0 onward.
minima:
  skin: dark
  date_format: "%b %d, %Y" # Customizable date format

# Social links in footer.
social_links:
  - platform: twitter
    user_url: "https://twitter.com/TenreiroDaniel"
