title: Daniel Tenreiro
author:
  name: Daniel Tenreiro

# The `>` after `description:` means to ignore line-breaks until next key.
description: >
  To speak in preexisting sayings linked to antiquity means to be a follower of the ways of the ancients. Although one seems to speak only accepted dogmas, in reality a criticism is hidden in it — "but it was the ancients who said so, not me!"

# Build settings
theme: minima
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
header_pages:
  - about.md
  - now.md

# Minima specific settings, available from Minima 3.0 onward.
minima:
  skin: dark
  date_format: "%b %d, %Y" # Customizable date format

# Social links in footer.
social_links:
  - platform: twitter
    user_url: "https://twitter.com/TenreiroDaniel"
